[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python start_railway.py && gunicorn run:app --bind 0.0.0.0:$PORT"

[env]
PYTHONPATH = "/app"
PORT = "5000"
FLASK_APP = "run.py"
